easy_admin:
    entities:
        Expense:
            class: 'Pehapkari\Provision\Entity\Expense'
            # see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/complex-dynamic-backends.html#customization-based-on-entity-controllers
            controller: 'Pehapkari\Provision\Controller\ExpenseController'
