easy_admin:
    # extension by config?
    # conditionally enable?

    # @see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/menu-configuration.html
    design:
        menu:
            -
                label: 'Uživatelé'
                icon: 'group'
                children: ['User', 'UserRole']

    entities:
        User:
            label: 'Uživatelé'
            class: 'OpenProject\User\Entity\User'
            form:
                fields: ['name', 'password', 'role']
        UserRole:
            label: 'Přístupové role'
            class: 'OpenProject\User\Entity\UserRole'
