# todo autoad!!!
controllers:
    resource: '../src/Controller/'
    type: annotation

# todo autoad!!!
package_controllers:
    resource: '../packages/RealEstate/src/Controller/'
    # resource: '../packages/*/Controller/'
    type: annotation
