easy_admin:
    entities:
        Registration:
            class: 'Pehapkari\Registration\Entity\TrainingRegistration'

            controller: 'Pehapkari\Registration\Admin\Controller\RegistrationController'

            list:
                batch_actions: ['certificate', 'sendInvoices']
                fields:
                    - 'name'
                    - 'email'
                    - 'trainingTerm'
                    - 'phone'
                    - 'ico'
                    - { property: 'participantCount', label: 'Persons?' }
                    - { property: 'hasInvoice', label: 'Invoice?' }
                    - { property: 'isPaid', label: 'Paid?' }
                    - { property: 'agreesWithPersonalData', label: 'GDPR', type: 'boolean' }
