parameters:
    certificate_assets_directory: '%kernel.project_dir%/public/assets/certificates'
    certificate_output_directory: '%kernel.project_dir%/public/generated/certificates'
    zip_output_directory: '%kernel.project_dir%/public/generated/zips'

    # fakturoid API
    fakturoid_slug: '%env(FAKTUROID_SLUG)%'
    fakturoid_email: '%env(FAKTUROID_EMAIL)%'
    fakturoid_api_key: '%env(FAKTUROID_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    OpenTraining\Training\:
        resource: '../src'
        exclude: '../src/{Entity}'

    Chumper\Zipper\Zipper: ~
