parameters:
    certificate_assets_directory: '%kernel.project_dir%/public/assets/certificate'
    certificate_output_directory: '%kernel.project_dir%/public/generated/certificate'

    zip_output_directory: '%kernel.project_dir%/public/generated/zips'

    promo_image_assets_directory: '%kernel.project_dir%/public/assets/promo_image'
    promo_image_output_directory: '%kernel.project_dir%/public/generated/promo_image'

    # fakturoid API
    fakturoid_slug: '%env(FAKTUROID_SLUG)%'
    fakturoid_email: '%env(FAKTUROID_EMAIL)%'
    fakturoid_api_key: '%env(FAKTUROID_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pehapkari\Training\:
        resource: '../src'
        exclude: '../src/{Entity}'

    Chumper\Zipper\Zipper: ~
