services:
    _defaults:
        public: true
        autowire: true

    OpenRealEstate\PriceMap\:
        resource: '..'
        exclude: '../{Entity}'

    PhpOffice\PhpSpreadsheet\Reader\Xls:
        calls:
            # better performance
            - ['setReadDataOnly', [true]]
