image: docker:git

deploy open-training:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - ssh root@$DEPLOY_HOST "cd /projects/open-training && ./run.sh"
  environment:
    name: production
    url: http://phpskoleni.cz
