image: docker:git

services:
  - docker:dind

variables:
  IMAGE: registry.gitlab.com/jm-tv-rename-later/open-project-jm-test

before_script:
  - echo $CI_BUILD_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin

build open-training image:
  stage: build
  script:
    - docker build --cache-from $IMAGE:latest -t $IMAGE:$CI_COMMIT_SHA -t $IMAGE:latest projects/open-training
    - docker push $IMAGE
