dist: trusty

jobs:
    include:
        - stage: build docker image
          script:
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              - docker pull pehapkari/pehapkari.cz || true
              - docker build --cache-from pehapkari/pehapkari.cz -t pehapkari/pehapkari.cz:$TRAVIS_COMMIT --target production -f Dockerfile .
              - docker push pehapkari/pehapkari.cz

        - stage: test
          script: docker run pehapkari/pehapkari.cz composer check-cs
        - script: docker run pehapkari/pehapkari.cz composer phpstan
        - script: docker run pehapkari/pehapkari.cz vendor/bin/phpunit
        - script: docker run pehapkari/pehapkari.cz bin/console lint:yaml src packages
        - script: docker run pehapkari/pehapkari.cz bin/console bin/console lint:twig packages templates
        - script: docker run pehapkari/pehapkari.cz bin/console composer dead-links

        - stage: deploy
          script:
            -  eval $(ssh-agent -s)
            - mkdir -p ~/.ssh
            - ssh-keyscan -H pehapkari.cz >> ~/.ssh/known_hosts
            - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
            - ssh root@pehapkari.cz "cd /projects/pehapkari.cz && ./run.sh"

# script:
    # tweets posts
#    - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then vendor/bin/statie tweet-post statie/source; fi

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
