dist: trusty

jobs:
    include:
        - stage: test key
          script:
              - echo $DEPLOY_PRIVATE_KEY
              - echo "$DEPLOY_PRIVATE_KEY"

        - stage: build docker image
          script:
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              - docker pull pehapkari/pehapkari.cz || true
              - docker build --cache-from pehapkari/pehapkari.cz -t pehapkari/pehapkari.cz:$TRAVIS_COMMIT --target production -f Dockerfile .
              - docker push pehapkari/pehapkari.cz

        - stage: test
          script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT composer check-cs
          name: ECS
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT composer phpstan
          name: PHPStan
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT php vendor/bin/phpunit
          name: PHPUnit
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT bin/console lint:yaml src packages
          name: Lint yaml
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT bin/console lint:twig packages templates
          name: Lint templates
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT composer dead-links
          name: Dead links

        - stage: deploy
          script:
            -  eval $(ssh-agent -s)
            - mkdir -p ~/.ssh
            - ssh-keyscan -H pehapkari.cz >> ~/.ssh/known_hosts
            - echo "$DEPLOY_PRIVATE_KEY" | ssh-add - > /dev/null
            - ssh root@pehapkari.cz "cd /projects/pehapkari.cz && ./run.sh"

# script:
    # tweets posts
#    - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then vendor/bin/statie tweet-post statie/source; fi

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
