language: php

php: 7.3

before_install:
    # disable xdebug to fasten process
    - phpenv config-rm xdebug.ini
    # make the script fail for any failed command
    - set -e

install:
    - composer update

script:
    - vendor/bin/phpunit

    # code analysis
    - composer check-cs
    - composer phpstan

    - bin/console lint:yaml src packages
    - bin/console lint:twig packages templates

notifications:
    email: false
