dist: trusty

jobs:
    include:
        - stage: build
          if: NOT type = cron
          name: Build docker image
          script:
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              - docker pull pehapkari/pehapkari.cz || true
              - docker build --cache-from pehapkari/pehapkari.cz -t pehapkari/pehapkari.cz:$TRAVIS_COMMIT --target production -f Dockerfile .
              - docker push pehapkari/pehapkari.cz

        - stage: test
          script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT composer check-cs
          name: ECS
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT composer phpstan
          name: PHPStan
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT php vendor/bin/phpunit
          name: PHPUnit
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT bin/console lint:yaml src packages
          name: Lint yaml
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT bin/console lint:twig packages templates
          name: Lint templates
        - script: docker run --rm pehapkari/pehapkari.cz:$TRAVIS_COMMIT composer dead-links
          name: Dead links
        - script: docker run --rm -e APP_ENV=prod pehapkari/pehapkari.cz:$TRAVIS_COMMIT bin/console cache:warmup
          name: Prod cache warmup

        - stage: deploy
          name: Deploy to pehapkari.cz
          if: branch = master AND type = push
          deploy:
              - provider: script
                script: sh bin/deploy.sh
                skip_cleanup: true

        - stage: deploy
          name: Deploy to new.pehapkari.cz
          if: branch = design-in-a-day
          deploy:
            - provider: script
              script: sh bin/deploy-new.sh
              skip_cleanup: true
              on:
                branch: design-in-a-day

        - stage: crons
          name: tweet posts
          if: branch = master AND type = cron
          script: vendor/bin/statie tweet-post statie/source

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
