language: php

php: 7.3

before_install:
    # disable xdebug to fasten process
    - phpenv config-rm xdebug.ini
    # make the script fail for any failed command
    - set -e

install:
    - composer update

script:
    - vendor/bin/phpunit

    # code analysis
    - composer check-cs
    - composer phpstan

    - bin/console lint:yaml src packages
    - bin/console lint:twig packages templates

    # testing posts are ok
    - vendor/bin/statie generate statie/source --output public

    # tweets posts
    - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then vendor/bin/statie tweet-post; fi

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
