language: php

matrix:
    fast_finish: true
    include:
        - php: '7.3'
          env: HTTP_STATUS_CHECK=true
        - php: '7.3'

before_install:
    # disable xdebug to fasten process
    - phpenv config-rm xdebug.ini
    # make the script fail for any failed command
    - set -e

install:
    - composer update

script:
    - if [[ HTTP_STATUS_CHECK == "" ]]; then vendor/bin/phpunit; fi

    # code analysis
    - if [[ HTTP_STATUS_CHECK == "" ]]; then composer check-cs; fi
    - if [[ HTTP_STATUS_CHECK == "" ]]; then composer phpstan; fi

    # linting
    - if [[ HTTP_STATUS_CHECK == "" ]]; then bin/console lint:yaml src packages; fi
    - if [[ HTTP_STATUS_CHECK == "" ]]; then bin/console lint:twig packages templates; fi

    # status check
    - if [[ HTTP_STATUS_CHECK == true ]]; then vendor/bin/http-status-check scan https://pehapkari.cz --output invalid-links.txt --ansi; fi

    # tweets posts
    - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then vendor/bin/statie tweet-post statie/source; fi

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
