language: php

matrix:
    include:
        - php: 7.1
        - php: 7.2
          env: CODE_ANALYSIS=true
        - php: 7.3

before_install:
    # disable xdebug to fasten process
    - phpenv config-rm xdebug.ini
    # make the script fail for any failed command
    - set -e

install:
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit

    # validate packages composer.json
    - vendor/bin/monorepo-builder validate

    # code analysis
    - |
      if [[ $CODE_ANALYSIS == true ]]; then
          composer check-cs
          composer phpstan
      fi

    - bin/console lint:yaml projects
    - bin/console lint:twig projects

notifications:
    email: false
