version: "3.7"
services:
    web:
        image: pehapkari_cz
        restart: unless-stopped
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=pehapkari_cz"
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/pehapkari.cz:cached
        tmpfs:
            - /var/www/pehapkari.cz/var/cache
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "pehapkari_cz"
        volumes:
            - ./.docker/mysql-data:/var/lib/mysql
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8081:8080
        depends_on:
            - mysql
