version: "3.7"
services:
    web:
        image: pehapkari_cz
        restart: always
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=pehapkari_cz"
            DATABASE_HOST: mysql
            DATABASE_USER: root
            DATABASE_PORT: 3306
            DATABASE_PASSWORD: root
            DATABASE_DBNAME: pehapkari_cz
            DATABASE_CHARSET: utf8
            DATABASE_URL: "mysql://root:root@mysql/pehapkari_cz?charset=utf8"
            APP_ENV: dev
            APP_DEBUG: 1
            APP_SECRET: 67d829bf61dc5f87a73fd814e2c9f629
            MAILER_URL: ""
            FAKTUROID_SLUG: ""
            FAKTUROID_EMAIL: ""
            FAKTUROID_API_KEY: ""
        ports:
            - "8080:80"
        volumes:
            - .:/app:cached
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "pehapkari_cz"
        volumes:
            - ./.docker/mysql-data:/var/lib/mysql
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        depends_on:
            - mysql
