easy_admin:
    list:
        max_results: 100
        actions:
            - { name: 'new', icon: 'plus', label: "Přidat" }
            - { name: 'edit', icon: 'pencil', label: "Upravit" }
            - { name: 'delete', icon: 'times',  label: "Smazat" }
            - { name: 'search', label: "Hledat" }
