parameters:
    organizers:
        # Prague
        -
            photo: "https://avatars2.githubusercontent.com/u/924196?s=460&v=4"
            name: "Tomáš Votruba"
            responsibility: "školení & srazy v Praze<br>vše, co je potřeba"
            url: "https://tomasvotruba.cz"
        -
            photo: "https://avatars0.githubusercontent.com/u/42802?s=460&v=4"
            name: "Honza Černý"
            responsibility: "PoSobota, PHP akce a konference"
            url: "https://honzacerny.com/"
        -
            photo: "https://avatars0.githubusercontent.com/u/3995003?s=400&v=4"
            name: "Jan Mikeš"
            responsibility: "hosting a deploy webu"
            url: "https://janmikes.cz"

        # Brno
        -
            photo: "madga_valaskova.jpg"
            name: "Magda Valášková"
            company: "oXyShop"
            company_url: "https://www.oxyshop.cz"
            responsibility: "srazy v Brně"
        -
            photo: "https://avatars1.githubusercontent.com/u/1753937?s=460&v=4"
            name: "Václav Čevela"
            company: "PeckaDesign"
            company_url: "https://www.peckadesign.cz"
            responsibility: "srazy v Brně"

        # Pardubice
        -
            photo: "https://avatars0.githubusercontent.com/u/695438?s=460&v=4"
            name: "Václav Pávek"
            responsibility: "PHP Pivo v Pardubicích"
            url: "https://www.vaclavpavek.cz"
        -
            photo: jan_kopp.jpg
            name: "Jan Kopp"
            company: "Digital Solutions"
            company_url: "https://www.digitalsolutions.cz"
            responsibility: "srazy v Pardubicích"

        -
            photo: "martin_prokes.jpg"
            name: "Martin Prokeš"
            company: "Elasticr"
            company_url: "https://www.elasticr.cz"
            responsibility: "srazy v Havlíčkově Brodě"

        -
            photo: "https://avatars1.githubusercontent.com/u/133822?s=460&v=4"
            name: "Jan Kuchař"
            responsibility: "livestreamy ze srazů"
            url: "https://grifart.cz"

        -
            photo: richard_koza.jpg
            name: "Richard Koza"
            responsibility: "příprava newsletteru"
            company: "UmímeWeby"
            company_url: "https://www.umimeweby.cz"
