imports:
    - { resource: "easy_admin.yaml" }

services:
    _defaults:
        autowire: true

    OpenRealEstate\Feed\:
        resource: '../src'
        exclude: '../src/{EasyAdmin/Configuration}'
