services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pehapkari\Registration\:
        resource: '../src'
        exclude: '../src/{Form,Exception,Entity,Api/FakturoidClient.php}'

    Pehapkari\Registration\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
