services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pehapkari\Registration\:
        resource: '../src'
        exclude: '../src/{Form,Exception,Entity,Api/FakturoidClient.php}'

    Pehapkari\Registration\Api\FakturoidClient:
        factory: ['@Pehapkari\Registration\Api\FakturoidClientFactory', 'create']
