parameters:
    locale: 'cs'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    OpenRealEstate\:
        resource: '../src/'
        exclude: '../src/Kernel.php'
