parameters:
    locale: 'cs'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    OpenRealEstate\:
        resource: '../src/'
        exclude: '../src/Kernel.php'

    # to be in EasyAdminExtensionBundle: https://github.com/alterphp/EasyAdminExtensionBundle/pull/57
    OpenProject\BetterEasyAdmin\Configuration\ExcludeFieldsConfigPass:
        tags:
            - { name: 'easyadmin.config_pass', priority: "120" }
