easy_admin:
    entities:
        TrainingTermProvision:
            class: 'Pehapkari\Training\Entity\TrainingTerm'
            controller: 'Pehapkari\Training\Controller\AdminTrainingTermController'
            list:
                sort: ['startDateTime', 'DESC']
                fields:
                    - 'training'
                    - 'participantCount'
                    - 'startDateTime'
                    - 'isProvisionPaid'
                actions:
                    -
                        name: 'training_term_provision'
                        type: 'route'
                        label: 'Provision'
                        css_class: 'btn btn-sm btn-warning'
