easy_admin:
    entities:
        TrainingTerm:
            label: 'Training Term'
            class: 'Pehapkari\Training\Entity\TrainingTerm'
            controller: 'Pehapkari\Training\Controller\AdminTrainingTermController'
            list:
                sort: ['startDateTime', 'DESC']
                batch_actions: ['generateMarketingEvents']
                # show only those without paid provision
                dql_filter: 'entity.isProvisionPaid = FALSE'
                fields:
                    - 'training'
                    - 'startDateTime'
                    - 'registrations'

                actions:
                    -
                        name: 'training_term_organization'
                        type: 'route'
                        label: 'Organize'
                        css_class: 'btn btn-success'
