easy_admin:
    entities:
        Lead:
            label: 'Leads'
            class: 'OpenRealEstate\Lead\Entity\Lead'
            form:
                # added by `Knp\DoctrineBehaviors\Model\Timestampable\Timestampable` trait
                exclude_fields: ['createdAt', 'updatedAt']

        LeadStatus:
            label: 'Lead Status'
            class: 'OpenRealEstate\Lead\Entity\LeadStatus'
