easy_admin:
    # @see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/menu-configuration.html
    design:
        menu:
            -
                 label: 'Reality'
                 icon: 'home'
                 children: ['RealEstate', 'Type', 'ReconstructionType']

    entities:
        RealEstate:
            label: 'Reality'
            class: 'OpenRealEstate\RealEstate\Entity\RealEstate'
            form:
                # added by `Knp\DoctrineBehaviors\Model\Timestampable\Timestampable` trait
                exclude_fields: ['createdAt', 'updatedAt']

        Type:
            label: 'Typy'
            class: 'OpenRealEstate\RealEstate\Entity\RealEstateType'

        ReconstructionType:
            label: 'Rekonstrukce'
            class: 'OpenRealEstate\RealEstate\Entity\ReconstructionType'
