parameters:
    locale: 'cs'
    training_max_references_to_show: 3
    training_image_path: "/uploads/images/trainings"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    OpenTraining\:
        resource: '../src/'
        exclude: '../src/{OpenTrainingKernel.php}'
