parameters:
    locale: 'cs'
    training_max_references_to_show: 3
    image_uploads: "/uploads/images/"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    OpenTraining\:
        resource: '../src/'
        exclude: '../src/{OpenTrainingKernel.php}'
