services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Pehapkari\Github\:
        resource: '../src'

    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~
