easy_admin:
    entities:
        Training:
            class: 'Pehapkari\Training\Entity\Training'
            form:
                fields:
                    - 'name'
                    - { property: 'description', type_options: { attr: { rows: '25' } } }
                    # TIP: custom template - with "{{ value }}" within
                    # - { property: 'ibu', template: 'EasyAdmin/Beer/fields/ibu.html.twig' }

        TrainingTerm:
            label: 'Training Term'
            class: 'Pehapkari\Training\Entity\TrainingTerm'
            controller: 'Pehapkari\Training\Admin\Controller\AdminTrainingTermController'
            list:
                batch_actions: ['generateMarketingCampaign']
                fields:
                    - 'training'
                    - 'startDateTime'
                    - 'registrations'
                    - 'isProvisionPaid'
                actions:
                    - { name: 'training_term_provision', type: 'route', label: 'Provize', css_class: 'btn btn-sm btn-warning' }

        Trainer:
            class: 'Pehapkari\Training\Entity\Trainer'

        Place:
            class: 'Pehapkari\Training\Entity\Place'

        Feedback:
            class: 'Pehapkari\Training\Entity\TrainingFeedback'

        Watchdog:
            class: 'Pehapkari\Training\Entity\Watchdog'
            list:
                fields:
                    - 'email'
                    - 'note'
                    - 'training'
                    - 'createdAt'
                    - 'isInformed'
