easy_admin:
    entities:
        Training:
            class: 'Pehapkari\Training\Entity\Training'
            fields:
                - { property: 'description', type_options: { label_attr: { class: 'col-lg-3' }, attr: { class: 'col-lg-9' } } }

        TrainingTerm:
            label: 'Training Term'
            class: 'Pehapkari\Training\Entity\TrainingTerm'
            list:
                fields:
                    - 'training'
                    - 'startDateTime'
                    - 'registrations'
                    - 'isProvisionPaid'
                actions:
                    - { name: 'download_certificates', type: 'route', label: 'Stáhnout certifikáty',  css_class: 'btn btn-sm btn-info' }
                    - { name: 'send_invoices', type: 'route', label: 'Poslat faktury',  css_class: 'btn btn-sm btn-danger' }
                    - { name: 'training_term_provision', type: 'route', label: 'Provize', css_class: 'btn btn-sm btn-warning' }

        Trainer:
            class: 'Pehapkari\Training\Entity\Trainer'

        Place:
            class: 'Pehapkari\Training\Entity\Place'

        Feedback:
            class: 'Pehapkari\Training\Entity\TrainingFeedback'

        Watchdog:
            class: 'Pehapkari\Training\Entity\Watchdog'
            list:
                fields:
                    - 'email'
                    - 'note'
                    - 'training'
                    - 'createdAt'
                    - 'isInformed'
