parameters:
    training_grid_fields:
        - 'name'
        - { property: 'image', type: 'image', base_path: '%training_image_path%' }
        - 'perex'
        - 'description'
        - 'capacity'
        - 'price'
        - 'place'
        - 'trainer'

easy_admin:
    entities:
        Training:
            label: 'Školení'
            class: 'OpenTraining\Training\Entity\Training'

            list:
                fields: "%training_grid_fields%"
            show:
                fields: "%training_grid_fields%"
            form:
                fields:
                    - 'name'
                    - { property: 'imageFile', type: 'file' }
                    - 'perex'
                    - 'description'
                    - 'capacity'
                    - 'price'
                    - 'place'
                    - 'trainer'

        TrainingTerm:
            label: 'Termíny školení'
            class: 'OpenTraining\Training\Entity\TrainingTerm'
            form:
                exclude_fields: ['registrations', 'slug']

        Trainer:
            label: 'Školitelé'
            class: 'OpenTraining\Training\Entity\Trainer'
            form:
                exclude_fields: ['trainings']
        Place:
            label: 'Školící místa'
            class: 'OpenTraining\Training\Entity\Place'

        Reference:
            label: 'Zpětné vazby'
            class: 'OpenTraining\Training\Entity\TrainingReference'
