easy_admin:
    # @see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/menu-configuration.html
    design:
        menu:
            -
                label: 'Cenová mapa'
                icon: 'money'
                entity: 'AreaPrice'

    entities:
        AreaPrice:
            label: 'Cenová mapa'
            class: 'OpenRealEstate\PriceMap\Entity\AreaPrice'
