parameters:
    # number of trainings done by trainers in old way - to calculate the provision
    # (this is just example - @todo complete from invoiced in Fakturoid
    finished_trainings_count:
        -
            user_id: 1
            trainigs_count: 1
