# template only routes → template

organize_meetup:
    path: 'zorganizujte-sraz'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'marketing/organize_meetup.twig'

become_trainer:
    path: 'zacni-skolit'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'training/become_trainer.twig'

sponsoring:
    path: 'zviditelnete-vasi-firmu'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'marketing/sponsoring.twig'

privacy_policy:
    path: 'ochrana-soukromi'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'homepage/privacy_policy.twig'

contact:
    path: 'kontakt'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'homepage/contact.twig'

for_speakers:
    path: 'for-speakers'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'meetup/for_speakers.twig'

# feedback
thank_you_for_feedback:
    path: 'diky-za-feedback'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'feedback/thank_you_for_feedback.twig'

place_detail:
    path: 'vzdelavej-se/misto-jablotron-holesovice'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'place/place_detail.twig'
