imports:
    - { resource: '../statie.yaml' }
    - { resource: '_data/*.yaml' }

parameters:
    locale: 'en' # for easy admin bundle
    image_uploads: "/uploads/images/"

# copied from Statie
twig:
    globals:
        main_page_title: "Děláš v PHP? Jsi jedním z nás"
        site_url: "https://pehapkari.cz"
        google_analytics_tracking_id: "UA-89860072-1"
        disqus_name: "pehapkari"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Pehapkari\:
        resource: '../src/'
        exclude:
            - '../src/PehapkariKernel.php'
            - '../src/Doctrine/Query/*'
            - '../src/ValueObject/*'

    Defr\Ares: ~
    GuzzleHttp\Client: ~
    ParsedownExtra:
        class: 'ParsedownExtra'

    Symplify\Statie\Generator\Generator:
        factory: ['@Pehapkari\DependencyInjection\StatieFactory', 'createGenerator']

    Symplify\Statie\Generator\RelatedItemsResolver:
        factory: ['@Pehapkari\DependencyInjection\StatieFactory', 'createRelatedItemsResolver']

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symplify\PackageBuilder\Reflection\PrivatesAccessor: ~

    # latte filters in twig
    Latte\Runtime\FilterExecutor: ~

    # email validator
    Egulias\EmailValidator\EmailValidator: ~
