imports:
    - { resource: '../statie.yaml' }
    - { resource: '_data/*.yaml' }

parameters:
    locale: 'cs'
    training_max_references_to_show: 3
    image_uploads: "/uploads/images/"

# copied from Statie
twig:
    globals:
        page_title: "Děláš v PHP? Jsi jedním z nás"
        site_url: "https://pehapkari.cz"
        google_analytics_tracking_id: "UA-89860072-1"
        disqus_name: "pehapkari"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $organizers: '%organizers%'
            $authors: '%authors%'
            $phpPrague: '%php_prague%'

    Pehapkari\:
        resource: '../src/'
        exclude: '../src/{PehapkariKernel.php}'

    Defr\Ares: ~
    GuzzleHttp\Client: ~
    ParsedownExtra:
        class: 'ParsedownExtra'

    Symplify\Statie\Generator\Generator:
        factory: ['@Pehapkari\DependencyInjection\StatieFactory', 'createGenerator']

    Symplify\Statie\Generator\RelatedItemsResolver:
        factory: ['@Pehapkari\DependencyInjection\StatieFactory', 'createRelatedItemsResolver']
