imports:
    - { resource: '../statie.yaml' }
    - { resource: '_data/*.yaml' }

parameters:
    locale: 'cs'
    training_max_references_to_show: 3
    image_uploads: "/uploads/images/"

# copied from Statie
twig:
    globals:
        page_title: "Děláš v PHP? Jsi jedním z nás"
        site_url: "https://pehapkari.cz"
        github_edit_url_start: "https://github.com/pehapkari/pehapkari.cz/edit/master/source/"
        github_show_url_start: "https://github.com/pehapkari/pehapkari.cz/tree/master/"
        google_analytics_tracking_id: "UA-89860072-1"
        disqus_name: "pehapkari"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $organizers: '%organizers%'
            $authors: '%authors%'
            $phpPrague: '%php_prague%'

    OpenTraining\:
        resource: '../src/'
        exclude: '../src/{OpenTrainingKernel.php}'

    Defr\Ares: ~
    GuzzleHttp\Client: ~

    Symplify\Statie\Generator\Generator:
        factory: ['@OpenTraining\DependencyInjection\StatieFactory', 'createGenerator']

    Symplify\Statie\Generator\RelatedItemsResolver:
        factory: ['@OpenTraining\DependencyInjection\StatieFactory', 'createRelatedItemsResolver']
