imports:
    - { resource: '../statie.yaml' }
    - { resource: '_data/*.yaml' }

parameters:
    locale: 'cs'
    training_max_references_to_show: 3
    image_uploads: "/uploads/images/"

# copied from Statie
twig:
    globals:
        google_analytics_tracking_id: "UA-89860072-1"
        disqus_name: "pehapkari"
        site_url: "%site_url%"
        github_show_url_start: '%github_show_url_start%'
        page_title: '%page_title%'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $organizers: '%organizers%'
            $authors: '%authors%'

    OpenTraining\:
        resource: '../src/'
        exclude: '../src/{OpenTrainingKernel.php}'

    Defr\Ares: ~
    GuzzleHttp\Client: ~

    Symplify\Statie\Generator\Generator:
        factory: ['@OpenTraining\DependencyInjection\StatieFactory', 'createGenerator']
