parameters:
    locale: 'cs'
    training_max_references_to_show: 3
    image_uploads: "/uploads/images/"

# copied from Statie
twig:
    globals:
        google_analytics_tracking_id: "UA-89860072-1"
        disqus_name: "pehapkari"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    OpenTraining\:
        resource: '../src/'
        exclude: '../src/{OpenTrainingKernel.php}'

    Defr\Ares: ~
    GuzzleHttp\Client: ~
