parameters:
    # exclude globally, if not explicitly listed
    easy_admin_exclude_fields: ['createdAt', 'updatedAt', 'createdBy', 'updatedBy']

easy_admin:
    design:
        menu:
            -
                label: 'Leady'
                children:
                    - { label: 'Seznam leadů', entity: 'Lead' }
                    - { label: 'Status', entity: 'LeadStatus' }

    entities:
        Lead:
            label: 'Leads'
            class: 'OpenRealEstate\Lead\Entity\Lead'

        LeadStatus:
            label: 'Lead Status'
            class: 'OpenRealEstate\Lead\Entity\LeadStatus'
