easy_admin:
    entities:
        Registration:
            label: 'Registrace'
            class: 'OpenTraining\Registration\Entity\TrainingRegistration'

            list:
                fields:
                    - 'name'
                    - 'email'
                    - 'trainingTerm'
                    - 'phone'
                    - 'ico'
                    - { property: 'hasInvoice', label: 'Invoice?' }
                    - { property: 'isPaid', label: 'Paid?' }
                    - { property: 'agreesWithPersonalData', label: 'GDPR', type: 'boolean' }
