services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pehapkari\Marketing\:
        resource: '../src/'
        exclude:
            - '../src/ValueObject/*'
