easy_admin:
    # @see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/menu-configuration.html
    design:
        menu:
            -
                label: 'Cenov치 mapa'
                icon: 'money'
                children:
                    - { label: 'Odhadnout cenu', route: 'price_map_estimate_price' }
                    # only super admin
                    # https://github.com/alterphp/EasyAdminExtensionBundle#hiding-not-entity-based-menu-entries-on-role-option
                    - { label: 'Cenov치 mapa', entity: 'PriceMap', role: 'ROLE_SUPER_ADMIN' }
                    - { label: 'Nahr치t XLS', route: 'price_map_upload_xls', role: 'ROLE_SUPER_ADMIN' }

    entities:
        PriceMap:
            label: 'Cenov치 mapa'
            class: 'OpenRealEstate\PriceMap\Entity\PriceMap'

