imports:
    - { resource: '../../../statie.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

        bind:
            # not sure why not autowired - @todo fix
            $organizers: '%organizers%'
            $authors: '%authors%'

    OpenTraining\Statie\:
        resource: '../src'

    Symplify\Statie\Generator\Generator:
        factory: ['@OpenTraining\Statie\DependencyInjection\StatieFactory', 'createGenerator']

twig:
    globals:
        github_show_url_start: '%github_show_url_start%'
        page_title: '%page_title%'