services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

        bind:
            # not sure why not autowired - @todo fix
            $organizers: '%organizers%'

    OpenTraining\Statie\:
        resource: '../src'
