easy_admin:
    design:
        brand_color: '#00A8C6'
        assets:
            # https://symfony.com/doc/master/bundles/EasyAdminBundle/book/design-configuration.html#loading-the-entire-bootstrap-framework
            css:
                - 'bundles/easyadmin/bootstrap-all.css'

        menu:
            -
                label: 'Terms'
                icon: 'calendar'
                entity: 'TrainingTerm'
            -
                icon: 'id-badge'
                entity: 'Registration'
            -
                label: 'Content'
                icon: 'train'
                children:
                    -
                        label: 'Trainers'
                        entity: 'Trainer'
                    -   label: 'Trainings'
                        entity: 'Training'

            -
                label: 'Marketing'
                icon: 'mail-bulk'
                entity: 'MarketingEvent'
            -
                icon: 'comment'
                entity: 'Feedback'
            -
                label: 'Expenses'
                icon: 'money'
                entity: 'Expense'
            -
                label: 'Generate Certificate'
                icon: 'plus'
                route: 'create_certificate'
            -
                label: '[CRON] Sync Paid Invoices'
                icon: 'sync'
                route: 'sync_paid_invoices'
