services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    OpenProject\BetterEasyAdmin\:
        resource: '../src'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symplify\PackageBuilder\Reflection\PrivatesAccessor: ~
